# Generated by Django 6.0.6 on 2026-07-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleventa',
            name='inventario_descontado',
            field=models.BooleanField(default=False),
        ),
    ]
