# Generated by Django 6.0.6 on 2026-07-03 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_detalleventa_inventario_descontado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleventa',
            options={'verbose_name': 'Detalle de venta', 'verbose_name_plural': 'Detalles de venta'},
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-fecha'], 'verbose_name': 'Venta', 'verbose_name_plural': 'Ventas'},
        ),
    ]
