# Generated by Django 6.0.7 on 2026-08-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0005_cleanup_legacy_detail_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
