# Generated by Django 6.0.7 on 2026-08-30 02:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0006_alter_detalleventa_cantidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteElectronico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_numerica', models.CharField(blank=True, max_length=50, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='La clave numérica debe contener exactamente 50 dígitos.', regex='^\\d{50}$')])),
                ('consecutivo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('tipo_comprobante', models.CharField(choices=[('FACTURA_ELECTRONICA', 'Factura electrónica'), ('TIQUETE_ELECTRONICO', 'Tiquete electrónico'), ('NOTA_CREDITO', 'Nota de crédito'), ('NOTA_DEBITO', 'Nota de débito')], max_length=24)),
                ('xml_generado', models.TextField(blank=True, null=True)),
                ('estado_hacienda', models.CharField(choices=[('BORRADOR', 'Borrador'), ('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('ACEPTADO', 'Aceptado'), ('RECHAZADO', 'Rechazado'), ('ERROR', 'Error')], default='BORRADOR', max_length=12)),
                ('mensaje_hacienda', models.TextField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('fecha_creado', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizado', models.DateTimeField(auto_now=True)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comprobantes_electronicos', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Comprobante electrónico',
                'verbose_name_plural': 'Comprobantes electrónicos',
                'ordering': ['-fecha_creado'],
                'indexes': [models.Index(fields=['estado_hacienda'], name='ventas_comp_estado__792202_idx'), models.Index(fields=['tipo_comprobante'], name='ventas_comp_tipo_co_f85c4e_idx'), models.Index(fields=['fecha_envio'], name='ventas_comp_fecha_e_3db4b1_idx')],
            },
        ),
    ]
