# Generated by Django 6.0.7 on 2026-07-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terceros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dias_credito',
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='dias_credito',
            field=models.PositiveSmallIntegerField(default=30),
        ),
    ]
