# Generated by Django 6.0.6 on 2026-07-01 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('PATRIMONIO', 'Patrimonio'), ('INGRESO', 'Ingreso'), ('GASTO', 'Gasto'), ('COSTO', 'Costo')], max_length=20)),
                ('naturaleza', models.CharField(choices=[('DEUDORA', 'Deudora'), ('ACREEDORA', 'Acreedora')], max_length=20)),
                ('nivel', models.PositiveSmallIntegerField(default=1)),
                ('permite_movimientos', models.BooleanField(default=True)),
                ('estado', models.BooleanField(default=True)),
                ('cuenta_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcuentas', to='contabilidad.cuentacontable')),
            ],
            options={
                'verbose_name': 'Cuenta contable',
                'verbose_name_plural': 'Cuentas contables',
                'ordering': ['codigo'],
            },
        ),
    ]
