# Generated by Django 6.0.7 on 2026-07-29 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('origen', models.CharField(choices=[('MANUAL', 'Manual'), ('VENTA', 'Venta'), ('COMPRA', 'Compra'), ('COBRO', 'Cobro'), ('PAGO', 'Pago')], default='MANUAL', max_length=20)),
                ('referencia', models.CharField(blank=True, default='', max_length=100)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONTABILIZADO', 'Contabilizado'), ('ANULADO', 'Anulado')], default='BORRADOR', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('contabilizado_en', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DetalleAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('debe', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('haber', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='contabilidad.asientocontable')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='contabilidad.cuentacontable')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PeriodoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cerrado', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-fecha_inicio'],
                'constraints': [models.CheckConstraint(condition=models.Q(('fecha_fin__gte', models.F('fecha_inicio'))), name='periodo_fechas_validas')],
            },
        ),
        migrations.AddConstraint(
            model_name='asientocontable',
            constraint=models.UniqueConstraint(condition=models.Q(('referencia', ''), _negated=True), fields=('origen', 'referencia'), name='asiento_origen_referencia_unica'),
        ),
        migrations.AddConstraint(
            model_name='detalleasiento',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('debe__gt', 0), ('haber', 0)), models.Q(('haber__gt', 0), ('debe', 0)), _connector='OR'), name='detalle_solo_debe_o_haber'),
        ),
    ]
