# Generated by Django 6.0.7 on 2026-07-29 07:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_catalogo_base'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='asientocontable',
            name='asiento_origen_referencia_unica',
        ),
        migrations.AlterField(
            model_name='asientocontable',
            name='referencia',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='asientocontable',
            constraint=models.UniqueConstraint(fields=('origen', 'referencia'), name='asiento_origen_referencia_unica'),
        ),
    ]
