# Generated by Django 6.0.7 on 2026-08-28 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_remove_asientocontable_asiento_origen_referencia_unica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientocontable',
            name='monto_transaccion',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Importe comercial de la operación que originó el asiento.', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='detalleasiento',
            name='tipo_movimiento',
            field=models.CharField(choices=[('GENERAL', 'Movimiento general'), ('VENTA', 'Reconocimiento de la venta'), ('COSTO_VENTA', 'Costo de venta / salida de inventario'), ('COMPRA', 'Reconocimiento de la compra'), ('COBRO', 'Cobro de cuenta por cobrar'), ('PAGO', 'Pago de cuenta por pagar'), ('IMPUESTO', 'Impuestos'), ('RETENCION', 'Retenciones'), ('DEVOLUCION', 'Devolución'), ('AJUSTE_INVENTARIO', 'Ajuste de inventario')], default='GENERAL', max_length=30),
        ),
    ]
