# Generated by Django 6.0.6 on 2026-07-03 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('terceros', '0001_initial'),
        ('ventas', '0003_alter_detalleventa_options_alter_venta_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaPorCobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('monto_original', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Parcial'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='PENDIENTE', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_por_cobrar', to='terceros.cliente')),
                ('venta', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_por_cobrar', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Cuenta por cobrar',
                'verbose_name_plural': 'Cuentas por cobrar',
                'ordering': ['fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='PagoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cuenta_por_cobrar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='finanzas.cuentaporcobrar')),
                ('medio_pago', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='terceros.mediopago')),
            ],
            options={
                'verbose_name': 'Pago de cliente',
                'verbose_name_plural': 'Pagos de clientes',
                'ordering': ['-fecha'],
            },
        ),
    ]
