# Generated by Django 6.0.7 on 2026-07-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_pagocliente_usuario_pagoproveedor_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocliente',
            name='anulado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagocliente',
            name='estado',
            field=models.CharField(choices=[('APLICADO', 'Aplicado'), ('ANULADO', 'Anulado')], default='APLICADO', max_length=20),
        ),
        migrations.AddField(
            model_name='pagoproveedor',
            name='anulado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pagoproveedor',
            name='estado',
            field=models.CharField(choices=[('APLICADO', 'Aplicado'), ('ANULADO', 'Anulado')], default='APLICADO', max_length=20),
        ),
    ]
