# Generated by Django 6.0.7 on 2026-07-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, default='', max_length=200)),
                ('identificacion', models.CharField(blank=True, default='', max_length=50)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('correo', models.EmailField(blank=True, default='', max_length=254)),
                ('direccion', models.TextField(blank=True, default='')),
                ('iva', models.DecimalField(decimal_places=2, default=13, max_digits=5)),
                ('moneda', models.CharField(choices=[('CRC', 'Colón costarricense'), ('USD', 'Dólar estadounidense')], default='CRC', max_length=3)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de empresa',
            },
        ),
    ]
