# Generated by Django 6.0.7 on 2026-07-29 07:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_roles_base'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('metodo', models.CharField(max_length=10)),
                ('ruta', models.CharField(max_length=255)),
                ('codigo_respuesta', models.PositiveSmallIntegerField()),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'ordering': ['-fecha'],
            },
        ),
    ]
